### ISSUE TITLE
getKline gives empty array

### ISSUE THREAD

**Issue by akshaynexus** [sakhnyuk/websocket-crypto-api#1]
GetKline gives a empty array as response when trying to get kline data form a CryptoBridge Pair

**Comment by sakhnyuk** [comment]
Hello.
Could you send a code example?

**Comment by akshaynexus** [comment]
Sure

**Comment by akshaynexus** [comment]
https://codesandbox.io/s/eager-flower-1ncg8?fontsize=14

**Comment by midnight-q** [comment]
You should set interval end start time parameters in getKline
Also symbol must not contains "BRIDGE." part

https://codesandbox.io/s/optimistic-wave-0cpsf?fontsize=14

**Comment by akshaynexus** [comment]
Thanks for the solution,looks like that fixes the problem i had.
